site_name: IRI2020 Rust Port
theme:
  name: material
  palette:
    scheme: slate

nav:
  - Home: index.md
  - Package & Math Model (Rust Part): package.md
  - Algorithmic Reference: algorithms.md
  - Porting Documentation: porting.md

plugins:
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js


